version: "3.9"
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app
      - media_data:/app/media
    env_file:
      - .env

volumes:
  db_data:
  media_data:
