# Generated by Django 5.2 on 2025-04-03 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialsection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.tutorialsection'),
        ),
        migrations.AddField(
            model_name='tutorialsection',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tutorialsection',
            name='title',
            field=models.CharField(default='Schritt', max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tutorials.question'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='keywords',
            field=models.CharField(help_text='Kommagetrennt, z.\u202fB. IFC, Modellierung, BIM', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorialsection',
            name='tutorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tutorials.tutorial'),
        ),
    ]
