# Generated by Django 5.2 on 2025-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorialsection_options_question_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.CharField(default='Sonstiges', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='difficulty',
            field=models.CharField(choices=[('leicht', 'Leicht'), ('mittel', 'Mittel'), ('schwer', 'Schwer'), ('expert', 'Expertenmodus')], default='mittel', max_length=20),
        ),
    ]
