# Generated by Django 5.2 on 2025-04-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_category_tutorial_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='program',
            field=models.CharField(help_text='Z.\u202fB. Revit, ArchiCAD, Solibri', max_length=100),
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
