# Generated by Django 5.2 on 2025-04-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_tutorial_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='category',
        ),
    ]
