# Generated by Django 5.2 on 2025-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_tutorial_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='series',
            field=models.CharField(blank=True, help_text='Optional: Titel der Tutorial-Serie', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='program_versions',
            field=models.ManyToManyField(blank=True, to='tutorials.programversion'),
        ),
    ]
