# Generated by Django 5.2 on 2025-04-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_programversion_tutorial_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='tutorials.tutorial')),
            ],
        ),
    ]
