# Generated by Django 5.2 on 2025-04-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_tutorialscreenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='attachments',
        ),
        migrations.CreateModel(
            name='TutorialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tutorials.tutorial')),
            ],
        ),
    ]
