# Generated by Django 5.2 on 2025-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_remove_tutorial_attachments_tutorialattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='program_versions',
        ),
        migrations.DeleteModel(
            name='TutorialAttachment',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='program_versions',
            field=models.CharField(blank=True, help_text='Mehrere Versionen kommagetrennt angeben, z.\u202fB. 2021, 2022', max_length=200),
        ),
    ]
