# Generated by Django 5.2 on 2025-04-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_remove_question_question_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
