# Generated by Django 5.2 on 2025-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answer_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_correct_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_correct_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_correct_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_correct_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_correct_5',
            field=models.BooleanField(default=False),
        ),
    ]
