# Generated by Django 5.2 on 2025-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_quiz_answer_1_quiz_answer_2_quiz_answer_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorial_images/'),
        ),
    ]
