# Generated by Django 5.2 on 2025-04-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_quiz_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
