# Generated by Django 5.2 on 2025-04-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0021_deinmodell_alter_tutorialsection_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeinModell',
        ),
    ]
