# Generated by Django 5.2 on 2025-04-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0022_delete_deinmodell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialsection',
            name='content',
            field=models.TextField(),
        ),
    ]
