# Generated by Django 5.2 on 2025-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0023_alter_tutorialsection_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialsection',
            name='video',
            field=models.FileField(blank=True, help_text='(optional) MP4-, WebM- oder Ogg-Video', null=True, upload_to='tutorial_videos/'),
        ),
    ]
