# Generated by Django 5.2 on 2025-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0026_tutorialsection_video_alter_tutorialsection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialsection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tutorial_videos/'),
        ),
    ]
