# Generated by Django 5.2 on 2025-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0029_tutorialreview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorialreview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tutorialreview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutorialreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
