# Generated by Django 5.2 on 2025-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0031_userprofile_delete_tutorialreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
