# Generated by Django 5.2 on 2025-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0034_tutorialrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialrating',
            name='stars',
        ),
        migrations.AddField(
            model_name='tutorialrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
            preserve_default=False,
        ),
    ]
